import type { Article } from "./types";

// Sample articles for demo mode - curated to showcase different sections and features
export const DEMO_ARTICLES: Article[] = [
  {
    uri: "nyt://article/demo-1",
    url: "https://www.nytimes.com/2024/01/15/us/politics/biden-congress-immigration.html",
    title: "Biden and Congress Near Deal on Border Security Package",
    abstract: "The bipartisan agreement would represent the most significant changes to immigration policy in decades, with new restrictions on asylum seekers and increased funding for border enforcement.",
    byline: "By Zolan Kanno-Youngs and Catie Edmondson",
    section: "U.S. Politics",
    subsection: "White House",
    publishedDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1569025743873-ea3a9ber936f?w=800&h=500&fit=crop",
    imageCaption: "President Biden speaking about immigration policy",
    keywords: ["Immigration", "Border Security", "Asylum", "Congress"],
    people: ["Biden, Joseph R Jr"],
    organizations: ["White House", "Senate", "Democratic Party"],
    locations: ["United States", "Washington (DC)"],
    materialType: "News",
    wordCount: 1200,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Washington",
    source: "The New York Times",
    relevanceScore: 92,
  },
  {
    uri: "nyt://article/demo-2",
    url: "https://www.nytimes.com/2024/01/15/technology/openai-gpt5-release.html",
    title: "OpenAI Announces GPT-5 with Unprecedented Reasoning Capabilities",
    abstract: "The new model demonstrates significant improvements in mathematical reasoning, coding, and complex problem-solving, raising both excitement and concerns about AI advancement.",
    byline: "By Cade Metz and Karen Weise",
    section: "Technology",
    subsection: "Artificial Intelligence",
    publishedDate: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1677442135136-760c813028c0?w=800&h=500&fit=crop",
    imageCaption: "OpenAI headquarters in San Francisco",
    keywords: ["Artificial Intelligence", "Machine Learning", "ChatGPT", "Technology"],
    people: ["Altman, Sam"],
    organizations: ["OpenAI", "Microsoft Corp"],
    locations: ["San Francisco (Calif)"],
    materialType: "News",
    wordCount: 1500,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Technology",
    source: "The New York Times",
    relevanceScore: 95,
  },
  {
    uri: "nyt://article/demo-3",
    url: "https://www.nytimes.com/2024/01/15/business/economy/fed-interest-rates.html",
    title: "Federal Reserve Signals Potential Rate Cuts in Coming Months",
    abstract: "With inflation showing signs of cooling, Fed officials indicated they may begin easing monetary policy sooner than previously expected, boosting market optimism.",
    byline: "By Jeanna Smialek",
    section: "Business",
    subsection: "Economy",
    publishedDate: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=800&h=500&fit=crop",
    imageCaption: "The Federal Reserve building in Washington",
    keywords: ["Interest Rates", "Inflation", "Monetary Policy", "Federal Reserve"],
    people: ["Powell, Jerome H"],
    organizations: ["Federal Reserve System"],
    locations: ["United States"],
    materialType: "News",
    wordCount: 1100,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Business",
    source: "The New York Times",
    relevanceScore: 88,
  },
  {
    uri: "nyt://article/demo-4",
    url: "https://www.nytimes.com/2024/01/15/science/climate-ocean-temperatures.html",
    title: "Ocean Temperatures Hit Record Highs for Third Consecutive Year",
    abstract: "Scientists warn that unprecedented ocean warming is accelerating ice melt, disrupting marine ecosystems, and contributing to more extreme weather patterns worldwide.",
    byline: "By Henry Fountain",
    section: "Science",
    subsection: "Climate",
    publishedDate: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1518837695005-2083093ee35b?w=800&h=500&fit=crop",
    imageCaption: "Warming oceans are affecting marine life globally",
    keywords: ["Climate Change", "Ocean Temperatures", "Global Warming", "Marine Biology"],
    people: [],
    organizations: ["National Oceanic and Atmospheric Administration"],
    locations: ["Pacific Ocean", "Atlantic Ocean"],
    materialType: "News",
    wordCount: 1300,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Science",
    source: "The New York Times",
    relevanceScore: 85,
  },
  {
    uri: "nyt://article/demo-5",
    url: "https://www.nytimes.com/2024/01/15/opinion/democracy-elections-2024.html",
    title: "The Stakes of 2024: Democracy on the Ballot",
    abstract: "This election will test whether American democratic institutions can withstand unprecedented pressures and whether voters will defend the principles of self-governance.",
    byline: "By David Brooks",
    section: "Opinion",
    subsection: "Columnists",
    publishedDate: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    imageUrl: null,
    imageCaption: null,
    keywords: ["Democracy", "Elections", "Voting", "Political Polarization"],
    people: [],
    organizations: [],
    locations: ["United States"],
    materialType: "Op-Ed",
    wordCount: 900,
    hasMultimedia: false,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Opinion",
    source: "The New York Times",
    relevanceScore: 82,
  },
  {
    uri: "nyt://article/demo-6",
    url: "https://www.nytimes.com/2024/01/15/world/europe/ukraine-russia-winter-offensive.html",
    title: "Ukraine Prepares for Potential Russian Winter Offensive",
    abstract: "As Western military aid faces delays, Ukrainian commanders are bolstering defenses along the eastern front while adapting to new battlefield realities.",
    byline: "By Andrew E. Kramer",
    section: "World",
    subsection: "Europe",
    publishedDate: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1646488060498-5c948f77f9a3?w=800&h=500&fit=crop",
    imageCaption: "Ukrainian soldiers on the front lines",
    keywords: ["Ukraine War", "Military", "Russia", "NATO"],
    people: ["Zelensky, Volodymyr"],
    organizations: ["NATO"],
    locations: ["Ukraine", "Russia"],
    materialType: "News",
    wordCount: 1400,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Foreign",
    source: "The New York Times",
    relevanceScore: 90,
  },
  {
    uri: "nyt://article/demo-7",
    url: "https://www.nytimes.com/2024/01/15/health/weight-loss-drugs-insurance.html",
    title: "Insurers Grapple with Surging Demand for Weight Loss Drugs",
    abstract: "The popularity of Ozempic and Wegovy is forcing health plans to make difficult decisions about coverage, balancing costs against potential long-term health benefits.",
    byline: "By Gina Kolata",
    section: "Health",
    subsection: "",
    publishedDate: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&h=500&fit=crop",
    imageCaption: "Weight loss medications have seen unprecedented demand",
    keywords: ["Weight Loss", "Obesity", "Health Insurance", "Pharmaceuticals"],
    people: [],
    organizations: ["Novo Nordisk"],
    locations: ["United States"],
    materialType: "News",
    wordCount: 1250,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Health",
    source: "The New York Times",
    relevanceScore: 78,
  },
  {
    uri: "nyt://article/demo-8",
    url: "https://www.nytimes.com/2024/01/15/arts/music/taylor-swift-eras-tour-record.html",
    title: "Taylor Swift's Eras Tour Becomes Highest-Grossing Concert Tour Ever",
    abstract: "The tour has generated over $1 billion in revenue, reshaping the music industry's understanding of what live performances can achieve.",
    byline: "By Joe Coscarelli",
    section: "Arts",
    subsection: "Music",
    publishedDate: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=500&fit=crop",
    imageCaption: "Taylor Swift performing on the Eras Tour",
    keywords: ["Music", "Concerts", "Pop Music", "Entertainment"],
    people: ["Swift, Taylor"],
    organizations: [],
    locations: ["United States"],
    materialType: "News",
    wordCount: 1000,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Culture",
    source: "The New York Times",
    relevanceScore: 75,
  },
  {
    uri: "nyt://article/demo-9",
    url: "https://www.nytimes.com/2024/01/15/sports/football/nfl-playoffs-predictions.html",
    title: "NFL Playoffs: Breaking Down the Conference Championship Matchups",
    abstract: "As four teams vie for a Super Bowl berth, we analyze the key battles and strategic decisions that could determine the outcomes.",
    byline: "By Benjamin Hoffman",
    section: "Sports",
    subsection: "Pro Football",
    publishedDate: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1566577739112-5180d4bf9390?w=800&h=500&fit=crop",
    imageCaption: "The road to the Super Bowl narrows",
    keywords: ["Football", "NFL Playoffs", "Super Bowl", "Sports"],
    people: [],
    organizations: ["National Football League"],
    locations: ["United States"],
    materialType: "News",
    wordCount: 1100,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Sports",
    source: "The New York Times",
    relevanceScore: 70,
  },
  {
    uri: "nyt://article/demo-10",
    url: "https://www.nytimes.com/2024/01/15/realestate/housing-market-spring.html",
    title: "Housing Market Shows Signs of Thawing as Spring Approaches",
    abstract: "After months of stagnation, inventory is slowly increasing and some sellers are adjusting prices, potentially opening opportunities for patient buyers.",
    byline: "By Sophie Kasakove",
    section: "Real Estate",
    subsection: "",
    publishedDate: new Date(Date.now() - 16 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 15 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=500&fit=crop",
    imageCaption: "For sale signs are becoming more common",
    keywords: ["Real Estate", "Housing Market", "Mortgages", "Home Prices"],
    people: [],
    organizations: [],
    locations: ["United States"],
    materialType: "News",
    wordCount: 950,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Real Estate",
    source: "The New York Times",
    relevanceScore: 65,
  },
  {
    uri: "nyt://article/demo-11",
    url: "https://www.nytimes.com/2024/01/15/technology/apple-vision-pro-review.html",
    title: "Apple Vision Pro: A Glimpse Into Computing's Spatial Future",
    abstract: "After spending a week with Apple's new headset, it's clear this device points toward something transformative, even if it's not quite there yet.",
    byline: "By Brian X. Chen",
    section: "Technology",
    subsection: "Personal Tech",
    publishedDate: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1617802690992-15d93263d3a9?w=800&h=500&fit=crop",
    imageCaption: "The Apple Vision Pro headset",
    keywords: ["Virtual Reality", "Apple Vision Pro", "Augmented Reality", "Consumer Electronics"],
    people: ["Cook, Timothy D"],
    organizations: ["Apple Inc"],
    locations: ["United States"],
    materialType: "Review",
    wordCount: 1600,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Technology",
    source: "The New York Times",
    relevanceScore: 93,
  },
  {
    uri: "nyt://article/demo-12",
    url: "https://www.nytimes.com/2024/01/15/us/politics/supreme-court-trump-ballot.html",
    title: "Supreme Court to Hear Arguments on Trump Ballot Eligibility",
    abstract: "The justices will consider whether states can disqualify the former president from ballots under the 14th Amendment's insurrection clause.",
    byline: "By Adam Liptak",
    section: "U.S. Politics",
    subsection: "Supreme Court",
    publishedDate: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1589994965851-a8f479c573a9?w=800&h=500&fit=crop",
    imageCaption: "The Supreme Court building",
    keywords: ["Supreme Court", "Elections", "14th Amendment", "Trump Disqualification"],
    people: ["Trump, Donald J"],
    organizations: ["Supreme Court"],
    locations: ["United States", "Washington (DC)"],
    materialType: "News",
    wordCount: 1350,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Washington",
    source: "The New York Times",
    relevanceScore: 96,
  },
  {
    uri: "nyt://article/demo-13",
    url: "https://www.nytimes.com/2024/01/15/business/nvidia-stock-ai-chips.html",
    title: "Nvidia's AI Chip Dominance Pushes Market Value Past $1.5 Trillion",
    abstract: "The company's graphics processors have become essential infrastructure for artificial intelligence, cementing its position as a cornerstone of the tech industry.",
    byline: "By Don Clark",
    section: "Business",
    subsection: "Technology",
    publishedDate: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&h=500&fit=crop",
    imageCaption: "Nvidia's CEO Jensen Huang",
    keywords: ["Semiconductors", "Artificial Intelligence", "Stock Market", "GPUs"],
    people: ["Huang, Jensen"],
    organizations: ["Nvidia Corporation"],
    locations: ["Silicon Valley (Calif)"],
    materialType: "News",
    wordCount: 1150,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Business",
    source: "The New York Times",
    relevanceScore: 91,
  },
  {
    uri: "nyt://article/demo-14",
    url: "https://www.nytimes.com/2024/01/15/books/review/best-books-2024.html",
    title: "The Most Anticipated Books of 2024",
    abstract: "From literary debuts to long-awaited sequels, here are the titles our editors are most excited to read in the coming year.",
    byline: "By The New York Times Book Review",
    section: "Books",
    subsection: "Book Review",
    publishedDate: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 19 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=800&h=500&fit=crop",
    imageCaption: "A stack of upcoming releases",
    keywords: ["Books", "Literature", "Fiction", "Nonfiction"],
    people: [],
    organizations: [],
    locations: [],
    materialType: "Feature",
    wordCount: 2000,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Culture",
    source: "The New York Times",
    relevanceScore: 68,
  },
  {
    uri: "nyt://article/demo-15",
    url: "https://www.nytimes.com/2024/01/15/world/middleeast/gaza-humanitarian-crisis.html",
    title: "U.N. Warns of Catastrophic Humanitarian Conditions in Gaza",
    abstract: "Aid agencies report severe shortages of food, water, and medical supplies as the conflict continues and access remains severely restricted.",
    byline: "By Raja Abdulrahim",
    section: "World",
    subsection: "Middle East",
    publishedDate: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=800&h=500&fit=crop",
    imageCaption: "Aid distribution in Gaza",
    keywords: ["Gaza Strip", "Humanitarian Aid", "Israel-Gaza War", "Middle East Conflict"],
    people: [],
    organizations: ["United Nations"],
    locations: ["Gaza Strip", "Israel"],
    materialType: "News",
    wordCount: 1200,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Foreign",
    source: "The New York Times",
    relevanceScore: 89,
  },
  {
    uri: "nyt://article/demo-16",
    url: "https://www.nytimes.com/2024/01/15/dining/restaurant-trends-2024.html",
    title: "The Restaurant Trends That Will Define 2024",
    abstract: "From hyper-local sourcing to technology-driven experiences, chefs and restaurateurs share what's next for the dining industry.",
    byline: "By Pete Wells",
    section: "Food",
    subsection: "Dining",
    publishedDate: new Date(Date.now() - 22 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 21 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=500&fit=crop",
    imageCaption: "Modern restaurant interiors are evolving",
    keywords: ["Restaurants", "Food", "Dining", "Culinary Trends"],
    people: [],
    organizations: [],
    locations: ["New York City"],
    materialType: "Feature",
    wordCount: 1400,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Food",
    source: "The New York Times",
    relevanceScore: 72,
  },
  {
    uri: "nyt://article/demo-17",
    url: "https://www.nytimes.com/2024/01/15/magazine/ai-creativity-future.html",
    title: "Can Machines Be Creative? The Debate Intensifies",
    abstract: "As AI tools generate increasingly sophisticated art, music, and writing, artists and philosophers grapple with fundamental questions about creativity and consciousness.",
    byline: "By Ezra Klein",
    section: "Magazine",
    subsection: "",
    publishedDate: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 23 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1655720828018-edd2daec9349?w=800&h=500&fit=crop",
    imageCaption: "AI-generated artwork raises questions about creativity",
    keywords: ["Artificial Intelligence", "Art", "Creativity", "Philosophy"],
    people: [],
    organizations: [],
    locations: [],
    materialType: "Feature",
    wordCount: 3500,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Magazine",
    source: "The New York Times",
    relevanceScore: 87,
  },
  {
    uri: "nyt://article/demo-18",
    url: "https://www.nytimes.com/2024/01/15/nyregion/nyc-congestion-pricing.html",
    title: "New York City's Congestion Pricing Set to Begin in June",
    abstract: "The first-in-the-nation program will charge drivers entering Manhattan below 60th Street, aiming to reduce traffic and fund transit improvements.",
    byline: "By Ana Ley",
    section: "New York",
    subsection: "N.Y.C.",
    publishedDate: new Date(Date.now() - 11 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1534430480872-3498386e7856?w=800&h=500&fit=crop",
    imageCaption: "Traffic entering Manhattan",
    keywords: ["Traffic Congestion", "Tolls", "Public Transit", "Urban Planning"],
    people: [],
    organizations: ["Metropolitan Transportation Authority"],
    locations: ["New York City", "Manhattan (NYC)"],
    materialType: "News",
    wordCount: 1050,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Metro",
    source: "The New York Times",
    relevanceScore: 76,
  },
  {
    uri: "nyt://article/demo-19",
    url: "https://www.nytimes.com/2024/01/15/climate/renewable-energy-record.html",
    title: "Renewable Energy Sources Hit Record 30% of Global Electricity",
    abstract: "Solar and wind power continue their rapid expansion, though experts say the pace must accelerate further to meet climate goals.",
    byline: "By Brad Plumer",
    section: "Climate",
    subsection: "",
    publishedDate: new Date(Date.now() - 13 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&h=500&fit=crop",
    imageCaption: "Solar panels and wind turbines",
    keywords: ["Renewable Energy", "Solar Power", "Wind Power", "Climate Change"],
    people: [],
    organizations: ["International Energy Agency"],
    locations: [],
    materialType: "News",
    wordCount: 1200,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Climate",
    source: "The New York Times",
    relevanceScore: 84,
  },
  {
    uri: "nyt://article/demo-20",
    url: "https://www.nytimes.com/2024/01/15/style/gen-z-workplace-expectations.html",
    title: "Gen Z Is Reshaping Workplace Expectations. Here's How.",
    abstract: "Young workers are pushing for flexibility, purpose-driven work, and mental health support, challenging traditional corporate norms.",
    byline: "By Emma Goldberg",
    section: "Style",
    subsection: "Work",
    publishedDate: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    updatedDate: new Date(Date.now() - 17 * 60 * 60 * 1000).toISOString(),
    imageUrl: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=500&fit=crop",
    imageCaption: "Young professionals in a modern office",
    keywords: ["Workplace Culture", "Generation Z", "Remote Work", "Employment"],
    people: [],
    organizations: [],
    locations: ["United States"],
    materialType: "Feature",
    wordCount: 1300,
    hasMultimedia: true,
    isInteractive: false,
    isLiveBlog: false,
    contentType: "text",
    desk: "Styles",
    source: "The New York Times",
    relevanceScore: 74,
  },
];

// Sample profile data for demo mode
export const DEMO_PROFILE = {
  sections: [
    { category: "section", value: "Technology", score: 85 },
    { category: "section", value: "U.S. Politics", score: 72 },
    { category: "section", value: "Business", score: 68 },
    { category: "section", value: "Science", score: 55 },
    { category: "section", value: "World", score: 48 },
  ],
  topics: [
    { category: "topic", value: "Artificial Intelligence", score: 92 },
    { category: "topic", value: "Climate Change", score: 65 },
    { category: "topic", value: "Elections", score: 58 },
    { category: "topic", value: "Federal Reserve", score: 45 },
    { category: "topic", value: "Supreme Court", score: 42 },
  ],
  journalists: [
    { category: "reporter", value: "Cade Metz", score: 38 },
    { category: "reporter", value: "Ezra Klein", score: 35 },
    { category: "reporter", value: "David Brooks", score: 28 },
  ],
  organizations: [
    { category: "organization", value: "OpenAI", score: 45 },
    { category: "organization", value: "Apple Inc", score: 38 },
    { category: "organization", value: "Federal Reserve System", score: 32 },
  ],
};

// Sample AI insights for demo mode
export const DEMO_INSIGHTS = `Based on your reading patterns, you show strong interest in **technology and AI developments**, particularly around companies like OpenAI and Apple. You're also engaged with **political coverage**, especially relating to elections, the Supreme Court, and policy decisions.

Your reading suggests you value in-depth analysis over breaking news, with a preference for long-form pieces in the Magazine and Opinion sections. You tend to follow specific journalists like Cade Metz for tech coverage and David Brooks for political commentary.

**Emerging interests**: Climate and renewable energy topics have been appearing more frequently in your reading history, suggesting a growing interest in environmental coverage.`;

// Sample clusters for demo mode
export const DEMO_CLUSTERS = [
  {
    id: "cluster-ai-tech",
    title: "AI Industry Developments",
    summary: "OpenAI announces GPT-5, Nvidia's market dominance grows, and Apple enters spatial computing. The AI race intensifies across the tech industry.",
    articleUris: ["nyt://article/demo-2", "nyt://article/demo-11", "nyt://article/demo-13", "nyt://article/demo-17"],
    keywords: ["Artificial Intelligence", "OpenAI", "Nvidia", "Apple"],
    timespanStart: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    timespanEnd: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cluster-politics-2024",
    title: "2024 Election & Democracy",
    summary: "The Supreme Court considers Trump's ballot eligibility while Congress works on immigration reform. Stakes for democracy dominate political discourse.",
    articleUris: ["nyt://article/demo-1", "nyt://article/demo-5", "nyt://article/demo-12"],
    keywords: ["Elections", "Supreme Court", "Democracy", "Immigration"],
    timespanStart: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    timespanEnd: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "cluster-climate",
    title: "Climate & Energy Transition",
    summary: "Record ocean temperatures underscore climate urgency as renewable energy reaches new milestones. The energy transition accelerates globally.",
    articleUris: ["nyt://article/demo-4", "nyt://article/demo-19"],
    keywords: ["Climate Change", "Renewable Energy", "Ocean Temperatures"],
    timespanStart: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    timespanEnd: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
